### ISSUE TITLE
Deploy service to the cloud

### ISSUE THREAD

**Issue by m-nomanWD** [m-nomanWD/lab-agile-planning#5]
**As a** Cloud Engineer   
 **I need** I can develop this service to the cloud   
 **So that** We offer a valuable service to our clients.
   
 ### Details and Assumptions
 *I may use IBM cloud 
 *Or may use AWS
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I have deploy to the cloud
 When User go to this URL
 Then Our services must be available on this URL 
 ```

**Comment by MNomanKhokher** [comment]
Hi Noman
